platform:ios, '7.0'
pod 'EGOCache'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 2.0'
pod 'SVPullToRefresh', '~>0.4.1'
pod 'SDWebImage'
pod 'WSAssetPickerController'
pod 'NSData+MD5Digest'
pod 'Base64'
pod 'MWPhotoBrowser'
pod 'BlocksKit'
pod 'FMDB'
